openapi: 3.0.0
info: 
  version: 1.0.0
  title: server API
  description: yaml file for description the response data

paths: 
  /api/{version}/getadlist:
    parameters:
      - $ref: '#/components/parameters/Version'

    post:
      summary: Get Ad List
      operationId: GetAdList

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetAdListRequest'

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAdListResponse'          

  /api/{version}/newad:
    parameters:
      - $ref: '#/components/parameters/Version'

    post:
      summary: New Ad
      operationId: NewAd

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewAdRequest'

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewAdResponse'           

  /api/{version}/getad:
    parameters:
      - $ref: '#/components/parameters/Version'

    post:
      summary: Get Ad
      operationId: GetAd

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetAdRequest'

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAdResponse'          

components:

  parameters:
    Version:
      name: version
      description: api version
      in: path
      schema:
        type: integer
      required: true

  schemas:

    GetAdRequest:
      type: object
      properties:
        id:
          type: integer
        fields:
          type: array
          items:
            type: string
            enum: 
              - description
              - links  
      required:
        - id
        - fields          

    GetAdResponse:
      type: object
      properties:
        title:  
          type: string
        link:
          type: string
        price:
          x-go-type: decimal.Decimal
          x-go-type-import:
            name: decimal
            path: github.com/shopspring/decimal
      required:
        - title
        - link
        - price

    GetAdListRequest:
      type: object
      properties:
        order:
          x-go-type: storage.OrdBy
          x-go-type-import:
            name: OrdBy
            path: avito-backend-trainee/internal/storage
          nullable: true
        offset:
          type: integer
        pagination:
          type: string
          nullable: true  
      required:
        - order
        - offset
        - pagination        

    GetAdListResponse:
      type: object
      properties:
        result:
          type: array
          items:
            $ref: '#/components/schemas/GetAdResponse' 
      required:
        - result     

    NewAdRequest:
      type: object
      properties:
        id:
          type: integer
        fields:
          type: string
          nullable: true  
      required:
        - title
        - link
        - price

    NewAdResponse:
      type: object
      properties:
        id:
          type: integer
        code:
          type: integer
      required:
        - id
        - code
                            
    
