openapi: 3.0.0
info: 
  version: 1.0.0
  title: server API
  description: yaml file for description the response data

paths: 
  /api/{version}/getadlist:
    parameters:
      - $ref: '#/components/parameters/Version'

    post:
      summary: Get Ad List
      operationId: GetAdList

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdListRequest'

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdListResponse'          

  /api/{version}/newad:
    parameters:
      - $ref: '#/components/parameters/Version'

    post:
      summary: New Ad
      operationId: NewAd

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewAdRequest'

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewAdResponse'           

  /api/{version}/getad:
    parameters:
      - $ref: '#/components/parameters/Version'

    post:
      summary: Get Ad
      operationId: GetAd

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetAdRequest'

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAdResponse'          

components:

  parameters:
    Version:
      name: version
      description: api version
      in: path
      schema:
        type: integer
      required: true

  schemas:

    GetAdRequest:
      type: object
      properties:
        id:
          type: integer
          format: int64
        fields:
          type: array
          items:
            type: string
            enum: 
              - description
              - links  
      required:
        - id
        - fields          

    GetAdResponse:
      x-go-type: storage.GetAdResponse
      x-go-type-import:
        name: GetAdResponse
        path: avito-backend-trainee/internal/storage  

    AdListRequest:
      type: object
      properties:
        order:
          x-go-type: storage.OrdBy
          x-go-type-import:
            name: OrdBy
            path: avito-backend-trainee/internal/storage
          nullable: true
        offset:
          type: integer
          format: int64
        pagination:
          type: string
          nullable: true  
      required:
        - order
        - offset
        - pagination        

    AdListResponse:
      type: array
      items:
        $ref: '#/components/schemas/GetAdResponse'   

    NewAdRequest:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        links:
          type: array
          items:
            type: string
        price:
          x-go-type: decimal.Decimal
          x-go-type-import:
            name: decimal
            path: github.com/shopspring/decimal        
      required:
        - name
        - description
        - links
        - price

    NewAdResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        code:
          type: integer
          format: int64
      required:
        - id
        - 
        
    Error:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
      required:
        - status
        - message          
                            
    
